# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/digital_twin.xdc

# IP: ip/mult_gen_u33_1/mult_gen_u33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_u33 || ORIG_REF_NAME==mult_gen_u33} -quiet] -quiet

# IP: ip/pll_1/pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] -quiet
