# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Desktop/JYD/Source_code/six_try/jyd/pipilined5/kldj.srcs2/Timing_info/Functional_Retime/project/functional_retime.srcs/sources_1/ip/IROM/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/JYD/Source_code/six_try/jyd/pipilined5/kldj.srcs2/Timing_info/Functional_Retime/project/functional_retime.gen/sources_1/ip/IROM/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Desktop/JYD/Source_code/six_try/jyd/pipilined5/kldj.srcs2/Timing_info/Functional_Retime/project/functional_retime.srcs/sources_1/ip/IROM/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/JYD/Source_code/six_try/jyd/pipilined5/kldj.srcs2/Timing_info/Functional_Retime/project/functional_retime.gen/sources_1/ip/IROM/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
