# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktop/JYD/Source_code/merge_dualport_bpu/jyd/pipilined5/digital_twin/digital_twin.srcs/sources_1/ip/mult_gen_u33/mult_gen_u33.xci
# IP: The module: 'mult_gen_u33' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/JYD/Source_code/merge_dualport_bpu/jyd/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/mult_gen_u33/mult_gen_u33_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_u33'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Desktop/JYD/Source_code/merge_dualport_bpu/jyd/pipilined5/digital_twin/digital_twin.srcs/sources_1/ip/mult_gen_u33/mult_gen_u33.xci
# IP: The module: 'mult_gen_u33' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/JYD/Source_code/merge_dualport_bpu/jyd/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/mult_gen_u33/mult_gen_u33_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_u33'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
