# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktop/JYD/Source_code/merge_dualport_bpu/jyd/pipilined5/digital_twin/digital_twin.srcs/sources_1/ip/DRAM_TDP_1/DRAM_TDP.xci
# IP: The module: 'DRAM_TDP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/JYD/Source_code/merge_dualport_bpu/jyd/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/DRAM_TDP_1/DRAM_TDP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM_TDP'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Desktop/JYD/Source_code/merge_dualport_bpu/jyd/pipilined5/digital_twin/digital_twin.srcs/sources_1/ip/DRAM_TDP_1/DRAM_TDP.xci
# IP: The module: 'DRAM_TDP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/JYD/Source_code/merge_dualport_bpu/jyd/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/DRAM_TDP_1/DRAM_TDP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM_TDP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
