# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.runs/synth_2/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_2" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.cache/wt [current_project]
set_property parent.project_path D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/imports/test_src/dram.coe
add_files D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/imports/test_src/irom.coe
add_files D:/DESKTOP/JYD/src0/irom.coe
add_files D:/DESKTOP/JYD/src0/dram.coe
add_files d:/DESKTOP/JYD/src1/irom.coe
add_files d:/DESKTOP/JYD/src1/dram.coe
read_verilog -library xil_defaultlib -sv {
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/counter.sv
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/display_seg.sv
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/dram_driver.sv
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/perip_bridge.sv
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/seg7.sv
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/student_top.sv
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/twin_controller.sv
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/uart.sv
  D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/new/top.sv
}
read_verilog -library xil_defaultlib {
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/define.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/KLDJ_alu.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/KLDJ_exu.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/KLDJ_idu.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/KLDJ_ifu.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/KLDJ_lsu.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/KLDJ_regfile.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/KLDJ_top.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/KLDJ_wbu.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/alu_add.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/alu_and.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/alu_or.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/alu_shifter.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/alu_slt.v
  D:/DESKTOP/JYD/KDLJ_SRC/pipilined5/kldj.srcs2/sources_1/imports/rtl/alu_xor.v
}
read_ip -quiet D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/ip/pll_1/pll.xci
set_property used_in_implementation false [get_files -all d:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/pll/pll_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/pll/pll.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/pll/pll_ooc.xdc]

read_ip -quiet D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/ip/IROM/IROM.xci
set_property used_in_implementation false [get_files -all d:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/IROM/IROM_ooc.xdc]

read_ip -quiet D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/sources_1/ip/DRAM/DRAM.xci
set_property used_in_implementation false [get_files -all d:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.gen/sources_1/ip/DRAM/DRAM_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/constrs_1/new/digital_twin.xdc
set_property used_in_implementation false [get_files D:/Desktop/JYD/KDLJ_SRC/pipilined5/digital_twin/digital_twin.srcs/constrs_1/new/digital_twin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7k325tffg900-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_2_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_2" END { }
